#pragma once

// First-pass OpenThread core config for the nRF54L15 Arduino integration.
//
// This header is intentionally narrow: it trims subsystems that are not part of
// the initial CPUAPP FTD attach/role bring-up while leaving the core Thread
// stack shape intact.

#define OPENTHREAD_CONFIG_PLATFORM_INFO "NRF54L15-Clean-CPUAPP"

// Use the repo PAL crypto entry points for the first staged-core bring-up so we
// do not depend on the incomplete staged mbedTLS checkout.
#define OPENTHREAD_CONFIG_CRYPTO_LIB OPENTHREAD_CONFIG_CRYPTO_LIB_PLATFORM
#define OPENTHREAD_CONFIG_AES_CONTEXT_SIZE 32
#define OPENTHREAD_CONFIG_HMAC_SHA256_CONTEXT_SIZE 256
#define OPENTHREAD_CONFIG_HKDF_CONTEXT_SIZE 64
#define OPENTHREAD_CONFIG_SHA256_CONTEXT_SIZE 128

#define OPENTHREAD_CONFIG_UPTIME_ENABLE 1
#define OPENTHREAD_CONFIG_LOG_LEVEL OT_LOG_LEVEL_INFO

#define OPENTHREAD_CONFIG_TCP_ENABLE 0

#define OPENTHREAD_CONFIG_BACKBONE_ROUTER_ENABLE 0

#define OPENTHREAD_CONFIG_BORDER_AGENT_ENABLE 0
#define OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE 0
#define OPENTHREAD_CONFIG_BORDER_ROUTING_ENABLE 0

#define OPENTHREAD_CONFIG_BLE_TCAT_ENABLE 0

#define OPENTHREAD_CONFIG_CHANNEL_MANAGER_ENABLE 0
#define OPENTHREAD_CONFIG_CHANNEL_MONITOR_ENABLE 0

// The current PAL does not provide hardware MAC security/frame-counter
// handling, so staged-core bring-up must keep these services in software.
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_ACK_TIMEOUT_ENABLE 1
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_RETRANSMIT_ENABLE 1
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_CSMA_BACKOFF_ENABLE 1
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_TX_SECURITY_ENABLE 1
#define OPENTHREAD_CONFIG_MAC_SOFTWARE_RX_ON_WHEN_IDLE_ENABLE 1

#define OPENTHREAD_CONFIG_COMMISSIONER_ENABLE 0
#define OPENTHREAD_CONFIG_JOINER_ENABLE 0

#define OPENTHREAD_CONFIG_DHCP6_CLIENT_ENABLE 0
#define OPENTHREAD_CONFIG_DHCP6_SERVER_ENABLE 0
#define OPENTHREAD_CONFIG_DNS_CLIENT_ENABLE 0
#define OPENTHREAD_CONFIG_DNSSD_SERVER_ENABLE 0

#define OPENTHREAD_CONFIG_ANNOUNCE_SENDER_ENABLE 0
#define OPENTHREAD_CONFIG_CHILD_SUPERVISION_INTERVAL 0
#define OPENTHREAD_CONFIG_CHILD_SUPERVISION_CHECK_TIMEOUT 0
#define OPENTHREAD_CONFIG_CHILD_SUPERVISION_OLDER_VERSION_CHILD_DEFAULT_INTERVAL 0
#define OPENTHREAD_CONFIG_DATASET_UPDATER_ENABLE 0
#define OPENTHREAD_CONFIG_HISTORY_TRACKER_ENABLE 0
#define OPENTHREAD_CONFIG_JAM_DETECTION_ENABLE 0
#define OPENTHREAD_CONFIG_LINK_METRICS_MANAGER_ENABLE 0
#define OPENTHREAD_CONFIG_LINK_RAW_ENABLE 0
#define OPENTHREAD_CONFIG_MULTICAST_DNS_ENABLE 0
#define OPENTHREAD_CONFIG_PARENT_SEARCH_ENABLE 0
#define OPENTHREAD_CONFIG_PING_SENDER_ENABLE 0
#define OPENTHREAD_CONFIG_SRP_CLIENT_ENABLE 0
#define OPENTHREAD_CONFIG_SRP_SERVER_ENABLE 0
#define OPENTHREAD_CONFIG_TMF_NETDIAG_CLIENT_ENABLE 0
#define OPENTHREAD_CONFIG_TMF_PROXY_DUA_ENABLE 0
#define OPENTHREAD_CONFIG_TMF_PROXY_MLR_ENABLE 0
#define OPENTHREAD_CONFIG_TIME_SYNC_ENABLE 0
