#ifndef NRF54L15_CLEAN_CORE_VERSION_GENERATED_H
#define NRF54L15_CLEAN_CORE_VERSION_GENERATED_H

#define ARDUINO_NRF54L15_CLEAN_VERSION_MAJOR 1
#define ARDUINO_NRF54L15_CLEAN_VERSION_MINOR 0
#define ARDUINO_NRF54L15_CLEAN_VERSION_PATCH 18
#define ARDUINO_NRF54L15_CLEAN_VERSION_PRERELEASE ""
#define ARDUINO_NRF54L15_CLEAN_VERSION_IS_PRERELEASE 0

#define ARDUINO_NRF54L15_CLEAN_VERSION_ENCODE(major, minor, patch) \
    (((major) * 10000UL) + ((minor) * 100UL) + (patch))

#define ARDUINO_NRF54L15_CLEAN_VERSION \
    ARDUINO_NRF54L15_CLEAN_VERSION_ENCODE( \
        ARDUINO_NRF54L15_CLEAN_VERSION_MAJOR, \
        ARDUINO_NRF54L15_CLEAN_VERSION_MINOR, \
        ARDUINO_NRF54L15_CLEAN_VERSION_PATCH)

#define ARDUINO_NRF54L15_CLEAN_VERSION_STRING "1.0.18"

#endif  // NRF54L15_CLEAN_CORE_VERSION_GENERATED_H
