#ifndef NRF54L15_CLEAN_CORE_VERSION_H
#define NRF54L15_CLEAN_CORE_VERSION_H

#define ARDUINO_NRF54L15_CLEAN_VERSION_MAJOR 0
#define ARDUINO_NRF54L15_CLEAN_VERSION_MINOR 1
#define ARDUINO_NRF54L15_CLEAN_VERSION_PATCH 65

#define ARDUINO_NRF54L15_CLEAN_VERSION_ENCODE(major, minor, patch) \
    (((major) * 10000UL) + ((minor) * 100UL) + (patch))

#define ARDUINO_NRF54L15_CLEAN_VERSION \
    ARDUINO_NRF54L15_CLEAN_VERSION_ENCODE( \
        ARDUINO_NRF54L15_CLEAN_VERSION_MAJOR, \
        ARDUINO_NRF54L15_CLEAN_VERSION_MINOR, \
        ARDUINO_NRF54L15_CLEAN_VERSION_PATCH)

#define ARDUINO_NRF54L15_CLEAN_VERSION_STRING "0.1.65"

#define NRF54L15_CLEAN_CORE_VERSION_MAJOR ARDUINO_NRF54L15_CLEAN_VERSION_MAJOR
#define NRF54L15_CLEAN_CORE_VERSION_MINOR ARDUINO_NRF54L15_CLEAN_VERSION_MINOR
#define NRF54L15_CLEAN_CORE_VERSION_PATCH ARDUINO_NRF54L15_CLEAN_VERSION_PATCH
#define NRF54L15_CLEAN_CORE_VERSION ARDUINO_NRF54L15_CLEAN_VERSION
#define NRF54L15_CLEAN_CORE_VERSION_STRING ARDUINO_NRF54L15_CLEAN_VERSION_STRING

#ifdef __cplusplus
namespace arduino {
namespace nrf54l15clean {
inline constexpr int kCoreVersionMajor = ARDUINO_NRF54L15_CLEAN_VERSION_MAJOR;
inline constexpr int kCoreVersionMinor = ARDUINO_NRF54L15_CLEAN_VERSION_MINOR;
inline constexpr int kCoreVersionPatch = ARDUINO_NRF54L15_CLEAN_VERSION_PATCH;
inline constexpr unsigned long kCoreVersion = ARDUINO_NRF54L15_CLEAN_VERSION;
inline constexpr const char kCoreVersionString[] = ARDUINO_NRF54L15_CLEAN_VERSION_STRING;
}  // namespace nrf54l15clean
}  // namespace arduino
#endif

#endif  // NRF54L15_CLEAN_CORE_VERSION_H
